"""add hardware_id to devices

Revision ID: a61f47297566
Revises: 0001_initial_schema
Create Date: 2026-02-06 16:41:52.605626
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a61f47297566"
down_revision = "0001_initial_schema"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.add_column(sa.Column("hardware_id", sa.String(), nullable=True))
        batch_op.create_unique_constraint("uq_devices_hardware_id", ["hardware_id"])
        batch_op.drop_column("battery_level")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.add_column(sa.Column("battery_level", sa.FLOAT(), nullable=True))
        batch_op.drop_constraint("uq_devices_hardware_id", type_="unique")
        batch_op.drop_column("hardware_id")
    # ### end Alembic commands ###
